#!/bin/bash
set -e
cd "${0%/*}"
cd ..
git pull

echo "%fastai V1 for PyTorch" > title.md
echo "%document created $(date)" >> title.md
echo "#Introduction" >> title.md
echo "This PDF has been generated by C. Klukas on the base of the fastai documentation, hosted at https://github.com/fastai/fastai_docs. Content authors are listed in the section **Credits**. The fastai documentation has been published under the Apache License, Version 2.0 (Apache License Version 2.0, January 2004 http://www.apache.org/licenses/). The terms of the license are listed under the section **License for Documentation**. This documents sections may be incomplete or appear in the wrong order. Go to http://docs.fast.ai/ to view the official online documentation of fastai." >> title.md
echo "#License for Documentation" > license_heading.md

cd docs_src
rm -f pdf/fastai_docu.pdf
parallel jupyter nbconvert --to markdown  ::: *.ipynb

for f in *.md; do
	sed -i '/VBox/d' $f
done

pandoc --toc --latex-engine=xelatex ../title.md ../AUTHORS.md ../CLA.md ../CODE-OF-CONDUCT.md ../CONTRIBUTING.md ../license_heading.md ../LICENSE index.md training.md basic_train.md train.md metrics.md callback.md callbacks.md callbacks.hooks.md callbacks.fp16.md callbacks.one_cycle.md callbacks.lr_finder.md callbacks.mixup.md callbacks.rnn.md callbacks.general_sched.md applications.md vision.md vision.learner.md vision.transform.md vision.image.md vision.data.md vision.models.md vision.models.unet.md text.md text.learner.md text.transform.md text.data.md text.models.md tabular.md tabular.transform.md tabular.data.md tabular.models.md collab.md overview.md data.md layers.md core.md torch_core.md gen_doc.md gen_doc.gen_notebooks.md gen_doc.nbdoc.md gen_doc.convert2html.md -o ../pdf/fastai_docu.pdf

rm -f ../license_heading.md ../title.md

rm -f *.md
rm -rf basic_train_files/
rm -rf callback_files/
rm -rf callbacks.general_sched_files/
rm -rf callbacks.hooks_files/
rm -rf callbacks.lr_finder_files/
rm -rf callbacks.one_cycle_files/
rm -rf training_files/
rm -rf vision.data_files/
rm -rf vision.image_files/
rm -rf vision.learner_files/
rm -rf vision.transform_files/
rm -rf vision_files/

echo "created documentation file: fastai_docu.pdf"
